version: '3'
    
services:
  web-prod:
    build:
        context: .
        dockerfile: Dockerfile.prod
    ports:
      - "80:3000"
    volumes:
      - .:/usr/src/app

  redis:
     image: redis

  database:
    image: postgres:9.6
    env_file:
      - .env/production/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: